before_script:
  - apt-get update -qq && apt-get install -y -qq libdcmtk2-dev libwrap0-dev libjsoncpp-dev libicu-dev zlib1g-dev libboost-dev libboost-filesystem-dev libboost-python-dev libboost-regex-dev libboost-test-dev liblog4cpp5-dev dcmtk cmake pkg-config ninja-build
  - mkdir build && cd build
  - cmake -G Ninja -D CMAKE_CXX_FLAGS=-std=c++11 ../

after_script:
  - pwd

odil:trusty:
  image: ubuntu:trusty
  script: ninja libodil.so

odil:xenial:
  image: ubuntu:xenial
  script: ninja libodil.so
