language: minimal

matrix:
  include:
    - name: "Debian 10 (Buster)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} debian_buster"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name debian_buster --rm debian:buster
      after_success:
        - docker kill debian_buster
    
    - name: "Ubuntu 20.04 (Focal)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} ubuntu_focal"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ubuntu_focal --rm ubuntu:focal
      after_success:
        - docker kill ubuntu_focal
    
    - name: "macOS 10.14 (Mojave)"
      os: osx
      osx_image: xcode11
      env: 
        - CI_TYPE=brew 
        - CMAKE_OPTIONS="-DBoost_NO_BOOST_CMAKE=ON"
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER=""
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup

script: |
  ${RUNNER} ./.ci/${CI_TYPE}/install
  ${RUNNER} ./.ci/${CI_TYPE}/build
  ${RUNNER} ./.ci/${CI_TYPE}/post_build
