language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: Architecture=amd64 Distribution=ubuntu/trusty Python=2 WORKSPACE=${TRAVIS_BUILD_DIR}
    # - os: osx
    #   compiler: clang
install:
  - pip install --user cpp-coveralls
  - export PATH=$(python -c 'import site; print(site.getuserbase())')/bin:${PATH}
  - env
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo -E sh ./.ci/deb/install; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./.ci/brew/install; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_OPTIONS="-D CMAKE_CXX_FLAGS=--coverage" MAKE_OPTIONS=$(nproc) ./.ci/deb/build; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then MAKE_OPTIONS=$(sysctl -n hw.ncpu) ./.ci/brew/build; fi
after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./.ci/deb/post_build; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./.ci/brew/post_build; fi
  - if [ "${CC}" = "gcc" ]; then coveralls --exclude examples --exclude tests --exclude-pattern '.*CMake[^/]+\.c(?:pp)?' --exclude-pattern "/usr/.*" --root=${WORKSPACE} --build-root ${WORKSPACE}/build > /dev/null; fi
