language: minimal
sudo: required
services:
  - docker

env:
  # Debian
  # TODO: CMAKE_OPTIONS: "-D CMAKE_CXX_FLAGS=--coverage"
  - { vendor: debian, version: stretch, python: 3 }
  - { vendor: debian, version: stretch, python: 2 }
  - { vendor: debian, version:  jessie, python: 3 }
  - { vendor: debian, version:  jessie, python: 2 }
  # Ubuntu
  - { vendor: ubuntu, version:  bionic, python: 3 }
  - { vendor: ubuntu, version:  bionic, python: 2 }
  - { vendor: ubuntu, version:  xenial, python: 3 }
  - { vendor: ubuntu, version:  xenial, python: 2 }
  - { vendor: ubuntu, version:  trusty, python: 3 }
  - { vendor: ubuntu, version:  trusty, python: 2 }

before_install:
  # TODO: -e CMAKE_OPTIONS=${CMAKE_OPTIONS}
  - |
    docker run -di \
      -e Python=${python} -e WORKSPACE=${TRAVIS_BUILD_DIR} \
      -e MAKE_OPTIONS="-j$(nproc)" \
      -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} \
      --name odil --rm \
      ${vendor}:${version}

install:
  - docker exec odil ${TRAVIS_BUILD_DIR}/.ci/deb/install
  #- docker exec odil pip${python} install -U --user cpp-coveralls
  # TODO: export PATH=$(python -c 'import site; print(site.getuserbase())')/bin:${PATH}

script:
  - docker exec odil ${TRAVIS_BUILD_DIR}/.ci/deb/build

after_success:
  - docker exec odil ${TRAVIS_BUILD_DIR}/.ci/deb/post_build
  #- docker exec odil coveralls -n -l build/coverage.info
