language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdcmtk2-dev libwrap0-dev libboost-test-dev dcmtk
  - sudo pip install cpp-coveralls
script: mkdir build && cd build && cmake -D CMAKE_CXX_FLAGS:STRING="-std=c++0x --coverage" ../ && make && ../tests/run.sh
after_success:
  - coveralls --exclude tests --gcov-options '\-lp'
