language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
python:
  - "2.7"
addons:
  apt:
    packages:
    - libdcmtk2-dev
    - libwrap0-dev
    - libjsoncpp-dev
    - libicu-dev
    - zlib1g-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-python-dev
    - libboost-regex-dev
    - libboost-test-dev
    - dcmtk
    - ninja-build
    - cmake
    - pkg-config
before_install:
  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew update
  # JSONCpp conflicts with json-c
  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew uninstall json-c
  # Boost is already installed with another version
  - [ "$TRAVIS_OS_NAME" = "osx" ] && ( brew unlink boost; brew install boost boost-python )
  - [ "$TRAVIS_OS_NAME" = "osx" ] && brew install dcmtk icu4c jsoncpp ninja
  - pip install --user cpp-coveralls nose
  - export PATH=$(python -c 'import site; print(site.getuserbase())')/bin:${PATH}
before_script:
  - export SRC_DIR=$PWD
  - mkdir build
  - cd build
  - export BIN_DIR=$PWD
  - CMAKE_CXX_FLAGS="-std=c++11"
  - [ "${CC}" = "gcc" ] && CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} --coverage"
  - [ "$TRAVIS_OS_NAME" = "linux" ] && PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so
  - [ "$TRAVIS_OS_NAME" = "osx" ] && PYTHON_LIBRARY=/usr/lib/libpython2.7.dylib
  - [ "$TRAVIS_OS_NAME" = "osx" ] && CMAKE_ARGUMENTS="-D ICU_INCLUDE_DIR=/usr/local/opt/icu4c/include/ -D ICU_LIBRARY=/usr/local/opt/icu4c/lib/libicuuc.dylib"
  - cmake -G Ninja -D CMAKE_CXX_FLAGS:STRING="${CMAKE_CXX_FLAGS}" -D CMAKE_BUILD_TYPE:STRING=Debug -D PYTHON_LIBRARY=${PYTHON_LIBRARY} ${CMAKE_ARGUMENTS} ../
script:
  - ninja
  - ../tests/run.sh
after_success:
  - [ "${CC}" = "gcc" ]; && ( coveralls --exclude examples --exclude tests --exclude-pattern '.*CMake[^/]+\.c(?:pp)?' --exclude-pattern "/usr/.*" --root=${SRC_DIR} --build-root ${BIN_DIR} > /dev/null )
