version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\odil

environment:
  BOOST_ROOT: C:/Libraries/boost_1_59_0
  BOOST_LIBRARYDIR: C:/Libraries/boost_1_59_0/lib64-msvc-14.0
  ICU_INCLUDE_DIR: C:/Libraries/icu/include
  ICU_LIBRARY: C:/Libraries/icu/lib64/icuuc.lib
  JsonCpp_INCLUDE_DIR: c:/Libraries/jsoncpp_0_10_5/include
  JsonCpp_LIBRARY: c:/Libraries/jsoncpp_0_10_5/lib/jsoncpp.lib
  DCMTK_INCLUDE_DIR: C:/Libraries/dcmtk-3.6.1_20150924/include
  DCMTK_LIBRARY: C:/Libraries/dcmtk-3.6.1_20150924/lib/dcmdata.lib

configuration:
  - Release

install:
  # ICU4C
- ps: Start-FileDownload http://download.icu-project.org/files/icu4c/56.1/icu4c-56_1-Win64-msvc10.zip
- 7z x -bd -oC:\Libraries icu4c-56_1-Win64-msvc10.zip
  # JsonCpp
- ps: Start-FileDownload https://github.com/lamyj/jsoncpp/releases/download/0.10.5/jsoncpp_0_10_5_Win64_msvc14.zip
- 7z x -bd -oC:\Libraries jsoncpp_0_10_5_Win64_msvc14.zip
  # DCMTK
- ps: Start-FileDownload https://github.com/lamyj/dcmtk/releases/download/DCMTK-3.6.1_20150924/dcmtk-3.6.1_20150924_Win64_msvc14.zip
- 7z x -bd -oC:\Libraries dcmtk-3.6.1_20150924_Win64_msvc14.zip

before_build:
  - cd c:\projects\odil
  - md build
  - cd build
  - cmake
    -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
    -DICU_INCLUDE_DIR="%ICU_INCLUDE_DIR%" -DICU_LIBRARY="%ICU_LIBRARY%"
    -DJsonCpp_INCLUDE_DIR="%JsonCpp_INCLUDE_DIR%" -DJsonCpp_LIBRARY="%JsonCpp_LIBRARY%"
    -DDCMTK_INCLUDE_DIR="%DCMTK_INCLUDE_DIR%" -DDCMTK_LIBRARY="%DCMTK_LIBRARY%"
    ..

build:
  project: C:\projects\odil\build\odil.sln
