version: "{build}"

os: Visual Studio 2015

clone_folder: c:\projects\dcmtkpp

environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - cd c:\projects\dcmtkpp
  - md build
  - cd build
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmake -G "Visual Studio 14 2015 Win64" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..

build:
  project: C:\projects\dcmtkpp\build\dcmtkpp.sln

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
