image: Visual Studio 2017
platform:
  - x64
version: '{build}'
branches:
  only:
    - master

configuration: Release

environment:
  VCPKG_EXPORT: vcpkg-export-20181101-093017
  VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
  ARCHITECTURE: x86_amd64

install:
  # This archive was obtained by:
  # vcpkg export --7zip --triplet x64-windows
  #   boost-asio boost-date-time boost-filesystem boost-fusion  boost-iostreams
  #   boost-lexical-cast boost-log boost-property-tree boost-spirit boost-test
  #   boost-uuid dcmtk icu jsoncpp pybind11 zlib
  - appveyor DownloadFile http://dl.bintray.com/lamyj/generic/vcpkg-exports/%VCPKG_EXPORT%.7z
  - 7z x %VCPKG_EXPORT%.7z -aos -oc:\tools\vcpkg
  - choco install ninja -y
  - vcpkg integrate install

before_build:
  - call "%VCVARSALL%" %ARCHITECTURE%
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - mkdir build
  - cd build
  - cmake
      -G Ninja -DCMAKE_MAKE_PROGRAM=C:/ProgramData/chocolatey/bin/ninja.exe
      -DCMAKE_BUILD_TYPE=%CONFIGURATION%
      -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/%VCPKG_EXPORT%/scripts/buildsystems/vcpkg.cmake
      -DBUILD_PYTHON_WRAPPERS=OFF -DUSE_BUILTIN_DCMTK_GETSCU=OFF
      -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install
      ..

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cmake --build .
  - cmake --build . --target install

test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - set PATH=%APPVEYOR_BUILD_FOLDER%\install\bin;%APPVEYOR_BUILD_FOLDER%\build\src;%PATH%
  - ctest -C Test -E "Association|Network|ServiceRole|SCP|SCU|Transport"
