version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\dcmtkpp

environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib64-msvc-12.0

platform:
  - x64

configuration:
  - RelWithDebInfo

before_build:
  - cd c:\projects\dcmtkpp
  - cmd: md build
  - cmd: cd build
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON"

build:
  project: C:\projects\dcmtkpp\build\dcmtkpp.sln
