version: build.{build}

os: Windows Server 2012 R2

clone_folder: c:\projects\dcmtkpp

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - echo "Running cmake..."
  - cd c:\projects\dcmtkpp
  - cmake --version
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - if %PLATFORM% == Win32 cmake .
  - if %PLATFORM% == x64 cmake -G "Visual Studio 12 2013 Win64" .

build:
  project: dcmtkpp.sln

