version: '{build}'
image: Visual Studio 2017
environment:
  PATH: C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;C:\Miniconda3-x64\Library\bin;$(PATH)
  PLATFORM: x64
  PYTHON: C:\Miniconda3-x64\python.exe
  VCVARS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
  WORKSPACE: $(APPVEYOR_BUILD_FOLDER)
branches:
  only:
    - master
    - appveyor
install:
  - call "%VCVARS_PATH%" %PLATFORM%
  - call .\.ci\windows\install.cmd
build_script:
  - call .\.ci\windows\build.cmd
test_script:
  - call .\.ci\windows\post_build.cmd
